export const TRAITS = {
  CARNIVORE: {
    color: '#ff4444',
    compatibleWith: ['FAST', 'STRONG'],
    hunts: ['HERBIVORE', 'OMNIVORE'],
    eats: [],
    baseSpeed: 3,
    baseSize: 8,
    energyLoss: 0.3,
    strength: 70,
  },
  HERBIVORE: {
    color: '#44ff44',
    compatibleWith: ['EFFICIENT', 'STRONG'],
    hunts: [],
    eats: ['PLANT'],
    baseSpeed: 2,
    baseSize: 6,
    energyLoss: 0.1,
    strength: 40,
  },
  OMNIVORE: {
    color: '#4444ff',
    compatibleWith: ['FAST', 'EFFICIENT', 'STRONG'],
    hunts: ['HERBIVORE'],
    eats: ['PLANT'],
    baseSpeed: 2.5,
    baseSize: 7,
    energyLoss: 0.2,
    strength: 55,
  },
  FAST: {
    color: '#ffff44',
    speedBonus: 1.5,
    energyLoss: 0.4,
    strength: 20,
  },
  EFFICIENT: {
    color: '#44ffff',
    energyLoss: 0.05,
    strength: 30,
  },
  STRONG: {
    color: '#ff44ff',
    strengthBonus: 1.5,
    energyLoss: 0.3,
    strength: 40,
  },
};